### ISSUE TITLE
raspberry Pi issue

### ISSUE THREAD

**Issue by reimannsum** [reimannsum/DangerBot#6]
The pi only has Python 3.4 which causes things to break

`pi@raspberrypi:~ $ python3 DangerBot/dangerbot/walker.py
  File "DangerBot/dangerbot/walker.py", line 99
    log_string = f"Log of {self.loc} at {self.pos} in {self.sub}\n"
                                                                  ^
SyntaxError: invalid syntax
`

**Comment by reimannsum** [comment]
https://docs.python.org/release/3.4.2/library/stdtypes.html#printf-style-string-formatting
`print('%(language)s has %(number)03d quote types.' %
...       {'language': "Python", "number": 2})
Python has 002 quote types.`
This is the string formatting available in 3.4.2

**Comment by reimannsum** [comment]
Thoughts on installing 3.7 from source?
https://www.wyre-it.co.uk/blog/latestpython/

**Comment by reimannsum** [comment]
fixed the strings but now I have another problem

`pi@raspberrypi:~ $ python3 DangerBot/dangerbot/walker.py
Traceback (most recent call last):
  File "DangerBot/dangerbot/walker.py", line 4, in <module>
    from dangerbot.suburb import Suburb
ImportError: No module named 'dangerbot'
pi@raspberrypi:~ $`
